import Head from 'next/head';
import Menu from './menu'
import style from '../styles/layout.module.css'
//destructuracion ({ x })
export default function Layout({children, title}){
return(
<div>
    <Head>
        <title>Gambo Merch {title?`| ${title}`: ""}</title>//valida si title existe sino imprime la seccion
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Menu />

    <div className={style.container}>{children}</div>
</div>
)
}